using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ParseTreeVisualizer.Util;

namespace ParseTreeVisualizer {
    public class TokenViewModel : Selectable<Token> {
        // we're deliberately not including IsError and TokenTypeID in the ViewModel; we don't want to display it in the autogenerated columns of the DataGrid
        public int Index => Model.Index;
        public string TokenType => Model.TokenType;
        public int Line => Model.Line;
        public int Col => Model.Col;
        public string Text => Model.Text;
        public (int start, int stop) Span => Model.Span;
        public bool IsWhitespace => Model.IsWhitespace;
        public TokenViewModel(Token model) : base(model) { }
    }
}
