//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Spitz\source\repos\AntlrBug_40\AntlrConsole3\Java9Parser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Java9Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IJava9ParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] Java9Parser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] Java9Parser.PrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericType([NotNull] Java9Parser.NumericTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.integralType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegralType([NotNull] Java9Parser.IntegralTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.floatingPointType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatingPointType([NotNull] Java9Parser.FloatingPointTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceType([NotNull] Java9Parser.ReferenceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOrInterfaceType([NotNull] Java9Parser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassType([NotNull] Java9Parser.ClassTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classType_lf_classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassType_lf_classOrInterfaceType([NotNull] Java9Parser.ClassType_lf_classOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classType_lfno_classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassType_lfno_classOrInterfaceType([NotNull] Java9Parser.ClassType_lfno_classOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceType([NotNull] Java9Parser.InterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceType_lf_classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceType_lf_classOrInterfaceType([NotNull] Java9Parser.InterfaceType_lf_classOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceType_lfno_classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceType_lfno_classOrInterfaceType([NotNull] Java9Parser.InterfaceType_lfno_classOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeVariable([NotNull] Java9Parser.TypeVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayType([NotNull] Java9Parser.ArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.dims"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDims([NotNull] Java9Parser.DimsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameter([NotNull] Java9Parser.TypeParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeParameterModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterModifier([NotNull] Java9Parser.TypeParameterModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeBound([NotNull] Java9Parser.TypeBoundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.additionalBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditionalBound([NotNull] Java9Parser.AdditionalBoundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArguments([NotNull] Java9Parser.TypeArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgumentList([NotNull] Java9Parser.TypeArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgument([NotNull] Java9Parser.TypeArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcard([NotNull] Java9Parser.WildcardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.wildcardBounds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcardBounds([NotNull] Java9Parser.WildcardBoundsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.moduleName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleName([NotNull] Java9Parser.ModuleNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.packageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageName([NotNull] Java9Parser.PackageNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] Java9Parser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.packageOrTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageOrTypeName([NotNull] Java9Parser.PackageOrTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.expressionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionName([NotNull] Java9Parser.ExpressionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodName([NotNull] Java9Parser.MethodNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.ambiguousName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmbiguousName([NotNull] Java9Parser.AmbiguousNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] Java9Parser.CompilationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.ordinaryCompilation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrdinaryCompilation([NotNull] Java9Parser.OrdinaryCompilationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.modularCompilation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModularCompilation([NotNull] Java9Parser.ModularCompilationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.packageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageDeclaration([NotNull] Java9Parser.PackageDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.packageModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageModifier([NotNull] Java9Parser.PackageModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportDeclaration([NotNull] Java9Parser.ImportDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.singleTypeImportDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleTypeImportDeclaration([NotNull] Java9Parser.SingleTypeImportDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeImportOnDemandDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeImportOnDemandDeclaration([NotNull] Java9Parser.TypeImportOnDemandDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.singleStaticImportDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleStaticImportDeclaration([NotNull] Java9Parser.SingleStaticImportDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.staticImportOnDemandDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticImportOnDemandDeclaration([NotNull] Java9Parser.StaticImportOnDemandDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDeclaration([NotNull] Java9Parser.TypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclaration([NotNull] Java9Parser.ModuleDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.moduleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDirective([NotNull] Java9Parser.ModuleDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.requiresModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequiresModifier([NotNull] Java9Parser.RequiresModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] Java9Parser.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.normalClassDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalClassDeclaration([NotNull] Java9Parser.NormalClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassModifier([NotNull] Java9Parser.ClassModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameters([NotNull] Java9Parser.TypeParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterList([NotNull] Java9Parser.TypeParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.superclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperclass([NotNull] Java9Parser.SuperclassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.superinterfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperinterfaces([NotNull] Java9Parser.SuperinterfacesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceTypeList([NotNull] Java9Parser.InterfaceTypeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] Java9Parser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBodyDeclaration([NotNull] Java9Parser.ClassBodyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassMemberDeclaration([NotNull] Java9Parser.ClassMemberDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclaration([NotNull] Java9Parser.FieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.fieldModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldModifier([NotNull] Java9Parser.FieldModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.variableDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaratorList([NotNull] Java9Parser.VariableDeclaratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] Java9Parser.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaratorId([NotNull] Java9Parser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer([NotNull] Java9Parser.VariableInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannType([NotNull] Java9Parser.UnannTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannPrimitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannPrimitiveType([NotNull] Java9Parser.UnannPrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannReferenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannReferenceType([NotNull] Java9Parser.UnannReferenceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannClassOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannClassOrInterfaceType([NotNull] Java9Parser.UnannClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannClassType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannClassType([NotNull] Java9Parser.UnannClassTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannClassType_lf_unannClassOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannClassType_lf_unannClassOrInterfaceType([NotNull] Java9Parser.UnannClassType_lf_unannClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannClassType_lfno_unannClassOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannClassType_lfno_unannClassOrInterfaceType([NotNull] Java9Parser.UnannClassType_lfno_unannClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannInterfaceType([NotNull] Java9Parser.UnannInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannInterfaceType_lf_unannClassOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannInterfaceType_lf_unannClassOrInterfaceType([NotNull] Java9Parser.UnannInterfaceType_lf_unannClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannInterfaceType_lfno_unannClassOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannInterfaceType_lfno_unannClassOrInterfaceType([NotNull] Java9Parser.UnannInterfaceType_lfno_unannClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannTypeVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannTypeVariable([NotNull] Java9Parser.UnannTypeVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unannArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnannArrayType([NotNull] Java9Parser.UnannArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclaration([NotNull] Java9Parser.MethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodModifier([NotNull] Java9Parser.MethodModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodHeader([NotNull] Java9Parser.MethodHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult([NotNull] Java9Parser.ResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclarator([NotNull] Java9Parser.MethodDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList([NotNull] Java9Parser.FormalParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameters([NotNull] Java9Parser.FormalParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameter([NotNull] Java9Parser.FormalParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableModifier([NotNull] Java9Parser.VariableModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.lastFormalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLastFormalParameter([NotNull] Java9Parser.LastFormalParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.receiverParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceiverParameter([NotNull] Java9Parser.ReceiverParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.throws_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrows_([NotNull] Java9Parser.Throws_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.exceptionTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionTypeList([NotNull] Java9Parser.ExceptionTypeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.exceptionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionType([NotNull] Java9Parser.ExceptionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodBody([NotNull] Java9Parser.MethodBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.instanceInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanceInitializer([NotNull] Java9Parser.InstanceInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.staticInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticInitializer([NotNull] Java9Parser.StaticInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDeclaration([NotNull] Java9Parser.ConstructorDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.constructorModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorModifier([NotNull] Java9Parser.ConstructorModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.constructorDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDeclarator([NotNull] Java9Parser.ConstructorDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.simpleTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeName([NotNull] Java9Parser.SimpleTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.constructorBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorBody([NotNull] Java9Parser.ConstructorBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.explicitConstructorInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitConstructorInvocation([NotNull] Java9Parser.ExplicitConstructorInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclaration([NotNull] Java9Parser.EnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] Java9Parser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enumConstantList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstantList([NotNull] Java9Parser.EnumConstantListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstant([NotNull] Java9Parser.EnumConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enumConstantModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstantModifier([NotNull] Java9Parser.EnumConstantModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enumBodyDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBodyDeclarations([NotNull] Java9Parser.EnumBodyDeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclaration([NotNull] Java9Parser.InterfaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.normalInterfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalInterfaceDeclaration([NotNull] Java9Parser.NormalInterfaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceModifier([NotNull] Java9Parser.InterfaceModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.extendsInterfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendsInterfaces([NotNull] Java9Parser.ExtendsInterfacesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceBody([NotNull] Java9Parser.InterfaceBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMemberDeclaration([NotNull] Java9Parser.InterfaceMemberDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.constantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantDeclaration([NotNull] Java9Parser.ConstantDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.constantModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantModifier([NotNull] Java9Parser.ConstantModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMethodDeclaration([NotNull] Java9Parser.InterfaceMethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.interfaceMethodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMethodModifier([NotNull] Java9Parser.InterfaceMethodModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.annotationTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeDeclaration([NotNull] Java9Parser.AnnotationTypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.annotationTypeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeBody([NotNull] Java9Parser.AnnotationTypeBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.annotationTypeMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeMemberDeclaration([NotNull] Java9Parser.AnnotationTypeMemberDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.annotationTypeElementDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementDeclaration([NotNull] Java9Parser.AnnotationTypeElementDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.annotationTypeElementModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationTypeElementModifier([NotNull] Java9Parser.AnnotationTypeElementModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultValue([NotNull] Java9Parser.DefaultValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] Java9Parser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.normalAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalAnnotation([NotNull] Java9Parser.NormalAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.elementValuePairList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValuePairList([NotNull] Java9Parser.ElementValuePairListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.elementValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValuePair([NotNull] Java9Parser.ElementValuePairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.elementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValue([NotNull] Java9Parser.ElementValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.elementValueArrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValueArrayInitializer([NotNull] Java9Parser.ElementValueArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.elementValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementValueList([NotNull] Java9Parser.ElementValueListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.markerAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMarkerAnnotation([NotNull] Java9Parser.MarkerAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.singleElementAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleElementAnnotation([NotNull] Java9Parser.SingleElementAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] Java9Parser.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.variableInitializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializerList([NotNull] Java9Parser.VariableInitializerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] Java9Parser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.blockStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatements([NotNull] Java9Parser.BlockStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] Java9Parser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.localVariableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclarationStatement([NotNull] Java9Parser.LocalVariableDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] Java9Parser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] Java9Parser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.statementNoShortIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementNoShortIf([NotNull] Java9Parser.StatementNoShortIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.statementWithoutTrailingSubstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementWithoutTrailingSubstatement([NotNull] Java9Parser.StatementWithoutTrailingSubstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.emptyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] Java9Parser.EmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledStatement([NotNull] Java9Parser.LabeledStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.labeledStatementNoShortIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledStatementNoShortIf([NotNull] Java9Parser.LabeledStatementNoShortIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] Java9Parser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.statementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementExpression([NotNull] Java9Parser.StatementExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.ifThenStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfThenStatement([NotNull] Java9Parser.IfThenStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.ifThenElseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfThenElseStatement([NotNull] Java9Parser.IfThenElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.ifThenElseStatementNoShortIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfThenElseStatementNoShortIf([NotNull] Java9Parser.IfThenElseStatementNoShortIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.assertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertStatement([NotNull] Java9Parser.AssertStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] Java9Parser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlock([NotNull] Java9Parser.SwitchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlockStatementGroup([NotNull] Java9Parser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.switchLabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchLabels([NotNull] Java9Parser.SwitchLabelsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchLabel([NotNull] Java9Parser.SwitchLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enumConstantName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstantName([NotNull] Java9Parser.EnumConstantNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] Java9Parser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.whileStatementNoShortIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatementNoShortIf([NotNull] Java9Parser.WhileStatementNoShortIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.doStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoStatement([NotNull] Java9Parser.DoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] Java9Parser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.forStatementNoShortIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatementNoShortIf([NotNull] Java9Parser.ForStatementNoShortIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.basicForStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicForStatement([NotNull] Java9Parser.BasicForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.basicForStatementNoShortIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicForStatementNoShortIf([NotNull] Java9Parser.BasicForStatementNoShortIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit([NotNull] Java9Parser.ForInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForUpdate([NotNull] Java9Parser.ForUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.statementExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementExpressionList([NotNull] Java9Parser.StatementExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enhancedForStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnhancedForStatement([NotNull] Java9Parser.EnhancedForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.enhancedForStatementNoShortIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnhancedForStatementNoShortIf([NotNull] Java9Parser.EnhancedForStatementNoShortIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] Java9Parser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] Java9Parser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] Java9Parser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.throwStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowStatement([NotNull] Java9Parser.ThrowStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.synchronizedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSynchronizedStatement([NotNull] Java9Parser.SynchronizedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.tryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryStatement([NotNull] Java9Parser.TryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.catches"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatches([NotNull] Java9Parser.CatchesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.catchClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchClause([NotNull] Java9Parser.CatchClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.catchFormalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchFormalParameter([NotNull] Java9Parser.CatchFormalParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.catchType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchType([NotNull] Java9Parser.CatchTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.finally_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinally_([NotNull] Java9Parser.Finally_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.tryWithResourcesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryWithResourcesStatement([NotNull] Java9Parser.TryWithResourcesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.resourceSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceSpecification([NotNull] Java9Parser.ResourceSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.resourceList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceList([NotNull] Java9Parser.ResourceListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource([NotNull] Java9Parser.ResourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.variableAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAccess([NotNull] Java9Parser.VariableAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] Java9Parser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray([NotNull] Java9Parser.PrimaryNoNewArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lf_arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lf_arrayAccess([NotNull] Java9Parser.PrimaryNoNewArray_lf_arrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lfno_arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lfno_arrayAccess([NotNull] Java9Parser.PrimaryNoNewArray_lfno_arrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lf_primary([NotNull] Java9Parser.PrimaryNoNewArray_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lf_primary_lf_arrayAccess_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lf_primary_lf_arrayAccess_lf_primary([NotNull] Java9Parser.PrimaryNoNewArray_lf_primary_lf_arrayAccess_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primary([NotNull] Java9Parser.PrimaryNoNewArray_lf_primary_lfno_arrayAccess_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lfno_primary([NotNull] Java9Parser.PrimaryNoNewArray_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lfno_primary_lf_arrayAccess_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lfno_primary_lf_arrayAccess_lfno_primary([NotNull] Java9Parser.PrimaryNoNewArray_lfno_primary_lf_arrayAccess_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.primaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primary([NotNull] Java9Parser.PrimaryNoNewArray_lfno_primary_lfno_arrayAccess_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassLiteral([NotNull] Java9Parser.ClassLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classInstanceCreationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInstanceCreationExpression([NotNull] Java9Parser.ClassInstanceCreationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classInstanceCreationExpression_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInstanceCreationExpression_lf_primary([NotNull] Java9Parser.ClassInstanceCreationExpression_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.classInstanceCreationExpression_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInstanceCreationExpression_lfno_primary([NotNull] Java9Parser.ClassInstanceCreationExpression_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgumentsOrDiamond([NotNull] Java9Parser.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.fieldAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccess([NotNull] Java9Parser.FieldAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.fieldAccess_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccess_lf_primary([NotNull] Java9Parser.FieldAccess_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.fieldAccess_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccess_lfno_primary([NotNull] Java9Parser.FieldAccess_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] Java9Parser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.arrayAccess_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess_lf_primary([NotNull] Java9Parser.ArrayAccess_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.arrayAccess_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess_lfno_primary([NotNull] Java9Parser.ArrayAccess_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodInvocation([NotNull] Java9Parser.MethodInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodInvocation_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodInvocation_lf_primary([NotNull] Java9Parser.MethodInvocation_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodInvocation_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodInvocation_lfno_primary([NotNull] Java9Parser.MethodInvocation_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] Java9Parser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodReference([NotNull] Java9Parser.MethodReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodReference_lf_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodReference_lf_primary([NotNull] Java9Parser.MethodReference_lf_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.methodReference_lfno_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodReference_lfno_primary([NotNull] Java9Parser.MethodReference_lfno_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.arrayCreationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayCreationExpression([NotNull] Java9Parser.ArrayCreationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.dimExprs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimExprs([NotNull] Java9Parser.DimExprsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.dimExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimExpr([NotNull] Java9Parser.DimExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpression([NotNull] Java9Parser.ConstantExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] Java9Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] Java9Parser.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaParameters([NotNull] Java9Parser.LambdaParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.inferredFormalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInferredFormalParameterList([NotNull] Java9Parser.InferredFormalParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaBody([NotNull] Java9Parser.LambdaBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] Java9Parser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] Java9Parser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.leftHandSide"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftHandSide([NotNull] Java9Parser.LeftHandSideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] Java9Parser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] Java9Parser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalOrExpression([NotNull] Java9Parser.ConditionalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalAndExpression([NotNull] Java9Parser.ConditionalAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] Java9Parser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] Java9Parser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] Java9Parser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] Java9Parser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] Java9Parser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpression([NotNull] Java9Parser.ShiftExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] Java9Parser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] Java9Parser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] Java9Parser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.preIncrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreIncrementExpression([NotNull] Java9Parser.PreIncrementExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.preDecrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreDecrementExpression([NotNull] Java9Parser.PreDecrementExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.unaryExpressionNotPlusMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpressionNotPlusMinus([NotNull] Java9Parser.UnaryExpressionNotPlusMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] Java9Parser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.postIncrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostIncrementExpression([NotNull] Java9Parser.PostIncrementExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.postIncrementExpression_lf_postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostIncrementExpression_lf_postfixExpression([NotNull] Java9Parser.PostIncrementExpression_lf_postfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.postDecrementExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostDecrementExpression([NotNull] Java9Parser.PostDecrementExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.postDecrementExpression_lf_postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostDecrementExpression_lf_postfixExpression([NotNull] Java9Parser.PostDecrementExpression_lf_postfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpression([NotNull] Java9Parser.CastExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Java9Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] Java9Parser.IdentifierContext context);
}
